version: "3.9"
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    # platform: linux/amd64
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      # MYSQL_USER: root
      MYSQL_PASSWORD: password
  web:
    platform: linux/x86_64
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: myapp_development
    depends_on:
      - db
